### ISSUE TITLE
missing sqlite3 dependency on ubuntu 22.04 (and others?)

### ISSUE THREAD

**Issue by aronatkins** [rstudio/python-builds#97]
After installing Python 3.11.9 into an ubuntu:22.04 image:

```bash
/opt/python/3.11.9/bin/python -c 'import sqlite3'
#> Traceback (most recent call last):
#>   File "<string>", line 1, in <module>
#>   File "/opt/python/3.11.9/lib/python3.11/sqlite3/__init__.py", line 57, in <module>
#>     from sqlite3.dbapi2 import *
#>   File "/opt/python/3.11.9/lib/python3.11/sqlite3/dbapi2.py", line 27, in <module>
#>     from _sqlite3 import *
#> ImportError: libsqlite3.so.0: cannot open shared object file: No such file or directory
```

Resolved by installing sqlite3.

```bash
apt-get install -y sqlite3
```

**Comment by edavidaja** [comment]
I can reproduce on noble; testing an updated build locally and will trigger a rebuild if successful.

**Comment by edavidaja** [comment]
We now recommend installing the standalone Python builds provided here: https://github.com/astral-sh/python-build-standalone

    See the updated documentation on installing Python: https://docs.posit.co/resources/install-python-uv.html

    Read more about installing python with uv: https://docs.astral.sh/uv/concepts/python-versions/#installing-a-python-version
